### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \escape: line 18 column 24 (char 536)

### ISSUE THREAD

**Issue by cyberserk** [FTM-Labs/Aptos-NFT-Mint#21]
>>python cli.py
Traceback (most recent call last):
  File "\aptos\aptosnftmint\script\src\cli.py", line 2, in <module>
    import create_candy_machine
  File "\aptos\aptosnftmint\script\src\create_candy_machine.py", line 12, in <module>
    import util
  File "\aptos\aptosnftmint\script\src\util.py", line 21, in <module>
    config = json.load(f)
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 18 column 24 (char 536)

**Comment by aycanozarpaci** [comment]
How to solved ? Can u tell me?
