### ISSUE TITLE
KeyError while uploading NFTs

### ISSUE THREAD

**Issue by MuskanBartaula** [FTM-Labs/Aptos-NFT-Mint#48]
=== Uploading NFT ===
Traceback (most recent call last):
  File "G:\tutorial\aptos\script\src\cli.py", line 20, in <module>
    candy_machine.create()
  File "G:\tutorial\aptos\script\src\candy_machine.py", line 133, in create
    self.uploadNftsToCm()
  File "G:\tutorial\aptos\script\src\candy_machine.py", line 223, in uploadNftsToCm
    tmp_metadata_uri = uriInfo["metadata_uri"]
KeyError: 'metadata_uri'

**Comment by vishrut66** [comment]
![2022-10-29 (2)](https://user-images.githubusercontent.com/108527286/198821358-ba19f734-c380-495d-8480-cace0ae2d068.png)
I also get the same error.

**Comment by razi429** [comment]
"=== Uploading NFT ===
Traceback (most recent call last):
File "G:\tutorial\aptos\script\src\cli.py", line 20, in
candy_machine.create()
File "G:\tutorial\aptos\script\src\candy_machine.py", line 133, in create
self.uploadNftsToCm()
File "G:\tutorial\aptos\script\src\candy_machine.py", line 223, in uploadNftsToCm
tmp_metadata_uri = uriInfo["metadata_uri"]
KeyError: 'metadata_uri'"



probably it is expecting the user to update the CID in metadata files..? am also stuck here btw. 
updating would have been easier if the ipfs upload was carried out as a folder instead of files. hashlips supports the CID update in this case.

**Comment by MuskanBartaula** [comment]
Delete the image_uris.json from the image folder and try again with cli.py command to create the candy machine. It works for me.
