### ISSUE TITLE
metadataUri & not enough funds in account errors

### ISSUE THREAD

**Issue by Lopezz11** [FTM-Labs/Aptos-NFT-Mint#51]
My problem is basically that i succesfuly uploaded my assets trough pinata, as the ipfs links to the images works proplerly, but at the time of trying to reupload my metadata, it pops up the next error:

=== Uploading NFT ===
Traceback (most recent call last):
  File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\cli.py", line 24, in <module>
    candy_machine.retryFailedUploads()
  File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\candy_machine.py", line 275, in retryFailedUploads
    self.uploadNftsToCm()
  File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\candy_machine.py", line 223, in uploadNftsToCm
    tmp_metadata_uri = uriInfo["metadata_uri"]
KeyError: 'metadata_uri'

In addition, if I try to do it by creating a CM with the same CM address, it pop up a different error:

Traceback (most recent call last):
File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\cli.py", line 20, in <module>
     candy_machine.create()
File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\candy_machine.py", line 122, in create
      self.prepareAccount()
File "C:\Users\xxx\yyyyyy\Aptos-NFT-Mint\script\src\candy_machine.py", line 78, in prepareAccount
       raise Exception("Not enough funds in account")
Exception: Not enough funds in account

What is causing my problem?, thanks in advance.

**Comment by Lopezz11** [comment]
solved by downgrading to python 3.9 (in my case)
