### ISSUE TITLE
candy machine creation error

### ISSUE THREAD

**Issue by drone42** [FTM-Labs/Aptos-NFT-Mint#60]
Hi,
=== Verifying assets and metadata ===
=== Upload assets to storage solution ===
Continuing previous storage upload...
Files that failed to upload: []
All images were uploaded successfully
=== Creating Candy Machine ===
Traceback (most recent call last):
  File "C:\apt\AptosNFTMint\script\src\cli.py", line 19, in <module>
    candy_machine.create()
  File "C:\apt\AptosNFTMint\script\src\candy_machine.py", line 119, in create
    self.createCandyMachine()
  File "C:\apt\AptosNFTMint\script\src\candy_machine.py", line 141, in createCandyMachine
    self.rest_client.wait_for_transaction(txn_hash)
  File "C:\Python311\Lib\site-packages\aptos_sdk\client.py", line 171, in wait_for_transaction
    assert (
AssertionError: {"version":"44301869","hash":"0x014bc0edbf...gas_used":"150","success":false,"vm_status":"Transaction Executed and Committed with Error LINKER_ERROR","accumulator_root_hash":"0...

What is the problem?
Thanks,

**Comment by samukolov** [comment]
+1

**Comment by samukolov** [comment]
> Hi, === Verifying assets and metadata === === Upload assets to storage solution === Continuing previous storage upload... Files that failed to upload: [] All images were uploaded successfully === Creating Candy Machine === Traceback (most recent call last): File "C:\apt\AptosNFTMint\script\src\cli.py", line 19, in candy_machine.create() File "C:\apt\AptosNFTMint\script\src\candy_machine.py", line 119, in create self.createCandyMachine() File "C:\apt\AptosNFTMint\script\src\candy_machine.py", line 141, in createCandyMachine self.rest_client.wait_for_transaction(txn_hash) File "C:\Python311\Lib\site-packages\aptos_sdk\client.py", line 171, in wait_for_transaction assert ( AssertionError: {"version":"44301869","hash":"0x014bc0edbf...gas_used":"150","success":false,"vm_status":"Transaction Executed and Committed with Error LINKER_ERROR","accumulator_root_hash":"0...
> 
> What is the problem? Thanks,

How did you solve it?

**Comment by drone42** [comment]
Hi, dont change contract address only cmpublic (your address) cmprivate(yourprivatekey)
