### ISSUE TITLE
Error in creating the Candy Machine

### ISSUE THREAD

**Issue by ghost** [FTM-Labs/Aptos-NFT-Mint#63]
=== Creating Candy Machine ===
Traceback (most recent call last):
  File "C:\work\Aptos-NFT-Mint-public\script\src\cli.py", line 19, in <module>
    candy_machine.create()
  File "C:\work\Aptos-NFT-Mint-public\script\src\candy_machine.py", line 119, in create
    self.createCandyMachine()
  File "C:\work\Aptos-NFT-Mint-public\script\src\candy_machine.py", line 140, in createCandyMachine
    txn_hash = self.rest_client.create_candy_machine(self.account)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\Aptos-NFT-Mint-public\script\src\client.py", line 56, in create_candy_machine
    signed_transaction = self.create_single_signer_bcs_transaction(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\Aptos-NFT-Mint-public\script\src\client.py", line 42, in create_single_signer_bcs_transaction
    signature = sender.sign(raw_transaction.keyed())
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aptos_sdk\transactions.py", line 89, in keyed
    self.serialize(ser)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aptos_sdk\transactions.py", line 115, in serialize
    self.payload.serialize(serializer)
  File "C:\work\Aptos-NFT-Mint-public\script\src\transactions.py", line 105, in serialize
    self.value.serialize(serializer)
  File "C:\work\Aptos-NFT-Mint-public\script\src\transactions.py", line 62, in serialize
    serializer.sequence(self.args, Serializer.bytes)
                                   ^^^^^^^^^^^^^^^^
AttributeError: type object 'Serializer' has no attribute 'bytes'

**Comment by bishthub** [comment]
any help till now? Still facing this issue

**Comment by CryptoAutistic80** [comment]
> === Creating Candy Machine ===
> Traceback (most recent call last):
> File "C:\work\Aptos-NFT-Mint-public\script\src\cli.py", line 19, in 
> candy_machine.create()
> File "C:\work\Aptos-NFT-Mint-public\script\src\candy_machine.py", line 119, in create
> self.createCandyMachine()
> File "C:\work\Aptos-NFT-Mint-public\script\src\candy_machine.py", line 140, in createCandyMachine
> txn_hash = self.rest_client.create_candy_machine(self.account)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\work\Aptos-NFT-Mint-public\script\src\client.py", line 56, in create_candy_machine
> signed_transaction = self.create_single_signer_bcs_transaction(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\work\Aptos-NFT-Mint-public\script\src\client.py", line 42, in create_single_signer_bcs_transaction
> signature = sender.sign(raw_transaction.keyed())
> ^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aptos_sdk\transactions.py", line 89, in keyed
> self.serialize(ser)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aptos_sdk\transactions.py", line 115, in serialize
> self.payload.serialize(serializer)
> File "C:\work\Aptos-NFT-Mint-public\script\src\transactions.py", line 105, in serialize
> self.value.serialize(serializer)
> File "C:\work\Aptos-NFT-Mint-public\script\src\transactions.py", line 62, in serialize
> serializer.sequence(self.args, Serializer.bytes)
> ^^^^^^^^^^^^^^^^
> AttributeError: type object 'Serializer' has no attribute 'bytes'

I recommend using WSL rather than windows, usually solves most issues. Just search for Ubuntu on Microsoft store.
